name: Sync Infisical secrets to github
on:
    workflow_dispatch:
        inputs:
            env:
                description: 'Environment to sync secrets to'
                type: choice
                required: true
                default: 'dev'
                options:
                    - dev
                    - staging
                    - prod
env:
    PHP_VERSION: 8.2

jobs:
    sync-infisical-secrets:
        # Only run on main branch
        # if: ${{ endsWith(github.ref, '/main') }}
        runs-on: ubuntu-latest
        steps:
            - name: Set github environment
              run: echo "TARGET_ENVIRONMENT=${{ inputs.env }}" >> $GITHUB_ENV
            - name: Set INFISICAL_TOKEN for dev
              if: ${{ 'dev' == github.event.inputs.env}}
              run: echo "INFISICAL_TOKEN=${{ secrets.DEV_INFISICAL_TOKEN }}" >> $GITHUB_ENV
            - name: Set INFISICAL_TOKEN for staging
              if: ${{ 'staging' == github.event.inputs.env }}
              run: echo "INFISICAL_TOKEN=${{ secrets.STAGING_INFISICAL_TOKEN }}" >> $GITHUB_ENV
            - name: Set INFISICAL_TOKEN for prod
              if: ${{ 'prod' == github.event.inputs.env }}
              run: echo "INFISICAL_TOKEN=${{ secrets.PROD_INFISICAL_TOKEN }}" >> $GITHUB_ENV

            - uses: actions/checkout@v3

            - name: Setup PHP ${{ env.PHP_VERSION }}
              uses: shivammathur/setup-php@v2
              with:
                  php-version: ${{ env.PHP_VERSION }}
                  extensions: sodium

            - name: Setup Infisical CLI
              run: |
                  sudo apt update && sudo apt install -y curl 
                  curl -1sLf 'https://dl.cloudsmith.io/public/infisical/infisical-cli/setup.deb.sh' | sudo bash
                  sudo apt update && sudo apt install -y infisical

            - name: Update secrets from Infisical
              run: REST_GITHUB_TOKEN=${{ secrets.REST_GITHUB_TOKEN }} php update_secrets.php
