name: Test Infisical Secrets Sync
on:
    workflow_dispatch:

jobs:
    test-sync-action:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v4
            - name: Test Infisical Secrets Sync
              uses: ./
              env:
                  REST_GITHUB_TOKEN: '${{ secrets.REST_GITHUB_TOKEN }}'
                  INFISICAL_TOKEN: '${{ secrets.STAGING_INFISICAL_TOKEN }}'
                  TARGET_ENVIRONMENT: 'staging'
